
import csv
import re

csv_path = r'd:\Master\SLR draft\data\SLR - SLR-Deep.csv'

# Define metric categories with keywords and citation keys
metric_definitions = [
    {
        "name": "Imperceptibility - Perplexity (PPL)",
        "keywords": ["PPL", "Perplexity"],
        "papers": []
    },
    {
        "name": "Imperceptibility - Statistical Divergence (KLD, JSD)",
        "keywords": ["KLD", "JSD", "KL Divergence", "Jensen-Shannon"],
        "papers": []
    },
    {
        "name": "Imperceptibility - Semantic Similarity (BLEU, SIM, SS)",
        "keywords": ["BLEU", "SIM", "SS", "SimCSE", "METEOR", "ROUGE", "Jaccard", "Cosine", "Semantic Similarity"],
        "papers": []
    },
    {
        "name": "Imperceptibility - Human Evaluation",
        "keywords": ["Human Evaluation"],
        "papers": []
    },
    {
        "name": "Imperceptibility - Diversity (TTR, Distinct-n)",
        "keywords": ["TTR", "Distinct-n", "Diversity"],
        "papers": []
    },
    {
        "name": "Security - Detection Accuracy (Acc)/F1-Score",
        "keywords": ["Acc", "Accuracy", "F1", "F1-Score", "Detection", "LS-CNN", "TS-RNN", "LS-BERT", "TS-CNN", "TS-CSW", "BiLSTM-Dense", "LS-RNN"],
        "papers": []
    },
    {
        "name": "Capacity - Bits Per Word / Token (BPW/BPT)",
        "keywords": ["BPW", "BPT", "Bits Per Word", "Bits Per Token", "ER", "Embedding Rate", "Capacity", "bps", "bits/word", "bits/token", "Payload"],
        "papers": []
    },
    {
        "name": "Capacity - Entropy Utilization",
        "keywords": ["Entropy Utilization", "Utilization"],
        "papers": []
    },
    {
        "name": "Robustness - Recovery Rate / Bit Match Rate",
        "keywords": ["Recovery Rate", "Bit Match Rate", "Complete Recovery Rate"],
        "papers": []
    },
    {
        "name": "Robustness - Resilience to Attacks (F1 drop)",
        "keywords": ["Resilience to Attacks", "F1 drop", "Attack"],
        "papers": []
    },
    {
        "name": "Efficiency - Generation / Extraction Time",
        "keywords": ["Time", "Generation Time", "Extraction Time", "Inference Latency"],
        "papers": []
    }
]

# Map paper titles to bib keys (from references)
title_to_bibkey = {
    "VAE-Stega: linguistic steganography based on variational auto-encoder": "yang2020vae",
    "General framework for reversible data hiding in texts based on masked language modeling": "zheng2022general",
    "Co-stega: Collaborative linguistic steganography for the low capacity challenge in social media": "liao2024co",
    "Joint linguistic steganography with BERT masked language model and graph attention network": "ding2023joint",
    "Discop: Provably secure steganography in practice based on\" distribution copies\"": "ding2023discop",
    "Generative text steganography with large language model": "wu2024generative",
    "Meteor: Cryptographically secure steganography for realistic distributions": "kaptchuk2021meteor",
    "Zero-shot generative linguistic steganography": "lin2024zero",
    "Provably secure disambiguating neural linguistic steganography": "qi2024provably",
    "A principled approach to natural language watermarking": "ji2024principled",
    "Context-aware linguistic steganography model based on neural machine translation": "ding2023context",
    "DeepTextMark: a deep learning-driven text watermarking approach for identifying large language model generated text": "munyer2024deeptextmark",
    "Hi-stega: A hierarchical linguistic steganography framework combining retrieval and generation": "wang2023hi",
    "Linguistic steganography: From symbolic space to semantic space": "zhang2020linguistic",
    "Natural language steganography by chatgpt": "steinebach2024natural",
    "Natural language watermarking via paraphraser-based lexical substitution": "qiang2023natural",
    "Rewriting-Stego: generating natural and controllable steganographic text with pre-trained language model": "li2023rewriting",
    "ALiSa: Acrostic linguistic steganography based on BERT and Gibbs sampling": "yi2022alisa",
    "Imperceptible Text Steganography based on Group Chat": "li2024imperceptible",
    "A Semantic Controllable Long Text Steganography Framework Based on LLM Prompt Engineering and Knowledge Graph": "li2024semantic",
    "Beyond Binary Classification: Customizable Text Watermark on Large Language Models": "xu2024beyond",
    "CPG-LS: Causal Perception Guided Linguistic Steganography": "xiang2023cpg",
    "Controllable Semantic Linguistic Steganography via Summarization Generation": "zhang2024controllable",
    "FREmax: A Simple Method Towards Truly Secure Generative Linguistic Steganography": "pang2024fremax",
    "Robust and semantic-faithful post-hoc watermarking of text generated by black-box language models": "hao2025robust",
    "Contrastive Semantic Watermarking Framework": "wang2025contrastive",
    "DeepStego": "kuznetsov2025deepstego",
    "Emotionally Controllable Steganography": "shi2025emotionally",
    "Multi-criteria Linguistic Optimization": "wozniak2025multicriteria",
    "Position-Agnostic Generation": "lin2025positionagnostic",
    "Two-Model Defense & Repair": "chen2025activetwo",
    "RS-Stega: A Token-Level Quality-Control Framework for Generative Text Steganography": "wang2025rsstega"
}

# Load and analyze CSV
with open(csv_path, 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    for row in reader:
        title = row.get('title', '').strip()
        if not title:
            continue
        
        eval_col = row.get('eval', '').strip()
        er_col = str(row.get('ER', '')).strip()
        combined_text = (eval_col + ' ' + er_col).lower()
        
        # Check each metric category
        for metric in metric_definitions:
            for keyword in metric["keywords"]:
                if keyword.lower() in combined_text:
                    if title not in [p["title"] for p in metric["papers"]]:
                        metric["papers"].append({
                            "title": title,
                            "bibkey": title_to_bibkey.get(title, "")
                        })
                    break

# Print results
print("=== All Metrics Analysis ===")
for metric in metric_definitions:
    print(f"\n{metric['name']}:")
    print(f"  Total count: {len(metric['papers'])}")
    print(f"  Papers:")
    for p in metric['papers']:
        label = p["title"]
        if p["bibkey"]:
            label += f" (\\cite{{{p['bibkey']}}})"
        print(f"    - {label}")
